// Paleta del sistema "Sierra" en claro y en oscuro: ÚNICA fuente de los colores.
//
// tailwind.config.js convierte cada token en `rgb(var(--c-<token>) / <alpha-value>)`,
// así que las clases de las pantallas (bg-surface, text-on-surface, bg-white…) no
// cambian: el tema se decide con variables CSS que un plugin del mismo config escribe
// en :root (claro), en [data-tema="oscuro"] y en "Auto" con el equipo en oscuro.
//
// - `white` (bg-white) es la SUPERFICIE: blanca en claro, verde muy oscuro en oscuro.
//   El texto sobre el botón negro usa `text-on-tinta` (no `text-white`).
// - Las hojas de las actas siguen el tema (decisión 2026-09-29); en oscuro la firma se
//   ve blanca (index.css, "Firmas en oscuro"). El PDF tiene sus propios colores.
// - Oscuro: la paleta de Tickets TIC (fondo #0e100e, superficie #171a17, marca clara).

export const CLARO = {
  white: '#ffffff',
  background: '#f4f5f1',
  'on-background': '#171717',
  surface: '#ffffff',
  'surface-bright': '#ffffff',
  'surface-container-lowest': '#ffffff',
  'surface-container-low': '#fafafa',
  'surface-container': '#f5f5f5',
  'surface-container-high': '#ebede7',
  'surface-container-highest': '#e5e5e5',
  'surface-dim': '#dcdcd6',
  'surface-variant': '#e5e5e5',
  'surface-blue': '#f5f5f5',
  'header-fill': '#f5f5f5',
  'surface-tint': '#171717',
  'on-surface': '#171717',
  'on-surface-variant': '#525252',
  'on-surface-subtle': '#6b6b6b',
  outline: '#a3a3a3',
  'outline-variant': '#e5e5e5',
  'border-muted': '#e5e5e5',
  primary: '#171717',
  'on-primary': '#ffffff',
  'primary-container': '#ebede7',
  'on-primary-container': '#171717',
  'primary-fixed': '#ebede7',
  'primary-fixed-dim': '#d4d4d4',
  'on-primary-fixed': '#171717',
  'on-primary-fixed-variant': '#404040',
  'inverse-primary': '#d4d4d4',
  secondary: '#525252',
  'secondary-container': '#f5f5f5',
  'on-secondary-container': '#262626',
  'secondary-fixed': '#f5f5f5',
  'secondary-fixed-dim': '#d4d4d4',
  'on-secondary-fixed': '#262626',
  'on-secondary-fixed-variant': '#404040',
  tertiary: '#171717',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#171717',
  'on-tertiary-container': '#737373',
  'tertiary-fixed': '#e5e5e5',
  'tertiary-fixed-dim': '#d4d4d4',
  'on-tertiary-fixed': '#171717',
  'on-tertiary-fixed-variant': '#404040',
  'inverse-surface': '#262626',
  'inverse-on-surface': '#f5f5f5',
  error: '#b3453b',
  'on-error': '#ffffff',
  'error-container': '#f1dcd9',
  'on-error-container': '#7a2f27',
  available: '#5b8a6b',
  'available-container': '#e3ede5',
  'on-available-container': '#3f6b4f',
  assigned: '#b58a3e',
  'assigned-container': '#f3ead6',
  'on-assigned-container': '#7a5a1e',
  papel: '#f4f5f1',
  tinta: '#0a0a0a',
  'tinta-hover': '#262626',
  'on-tinta': '#ffffff',
  bosque: '#0b2a1e',
  brote: '#4d7c2a',
  linea: '#9bc96a',
  exito: '#15803d',
  foco: '#2563eb',
  'foco-hover': '#1e40af',
  // Lo elegido (ítem activo del menú, chip/filtro/pestaña elegida, fila marcada):
  // tiene que distinguirse en claro y en oscuro.
  'sel-bg': '#ffffff',
  'sel-borde': '#e5e5e5',
  'sel-sutil': '#f5f5f5',
  'seg-on': '#e1e5dc',
  'seg-borde': '#c6ccc0',
}

export const OSCURO = {
  white: '#171a17',
  background: '#0e100e',
  'on-background': '#eaedea',
  surface: '#171a17',
  'surface-bright': '#171a17',
  'surface-container-lowest': '#171a17',
  'surface-container-low': '#1b1e1b',
  'surface-container': '#212521',
  'surface-container-high': '#272b27',
  'surface-container-highest': '#323731',
  'surface-dim': '#0e100e',
  'surface-variant': '#323731',
  'surface-blue': '#212521',
  'header-fill': '#212521',
  'surface-tint': '#eaedea',
  'on-surface': '#eaedea',
  'on-surface-variant': '#b9bfb8',
  'on-surface-subtle': '#9ba29a',
  outline: '#6d746c',
  'outline-variant': '#323731',
  'border-muted': '#323731',
  primary: '#eaedea',
  'on-primary': '#171a17',
  'primary-container': '#272b27',
  'on-primary-container': '#eaedea',
  'primary-fixed': '#272b27',
  'primary-fixed-dim': '#434942',
  'on-primary-fixed': '#eaedea',
  'on-primary-fixed-variant': '#ccd1cb',
  'inverse-primary': '#434942',
  secondary: '#b9bfb8',
  'secondary-container': '#212521',
  'on-secondary-container': '#dde1dc',
  'secondary-fixed': '#212521',
  'secondary-fixed-dim': '#434942',
  'on-secondary-fixed': '#dde1dc',
  'on-secondary-fixed-variant': '#ccd1cb',
  tertiary: '#eaedea',
  'on-tertiary': '#171a17',
  'tertiary-container': '#eaedea',
  'on-tertiary-container': '#9ba29a',
  'tertiary-fixed': '#323731',
  'tertiary-fixed-dim': '#434942',
  'on-tertiary-fixed': '#eaedea',
  'on-tertiary-fixed-variant': '#ccd1cb',
  'inverse-surface': '#dde1dc',
  'inverse-on-surface': '#212521',
  error: '#f27070',
  'on-error': '#171a17',
  'error-container': '#401818',
  'on-error-container': '#f6b4ad',
  available: '#6fbf8a',
  'available-container': '#123520',
  'on-available-container': '#9fd9b0',
  assigned: '#d9ae5c',
  'assigned-container': '#3a2d0e',
  'on-assigned-container': '#f0cf85',
  papel: '#0e100e',
  tinta: '#e3ece5',
  'tinta-hover': '#c9d6cc',
  'on-tinta': '#0e100e',
  bosque: '#5d7d68',
  brote: '#8fc46a',
  linea: '#9bc96a',
  exito: '#3cc873',
  foco: '#6b9bff',
  'foco-hover': '#a4c1ff',
  'sel-bg': '#394139',
  'sel-borde': '#4d564d',
  'sel-sutil': '#2b322b',
  'seg-on': '#3d463d',
  'seg-borde': '#5e685e',
}

// '#rrggbb' → 'r g b' (canales para rgb(var(--c-x) / alfa)).
export function canales(hex) {
  const n = parseInt(hex.slice(1), 16)
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`
}

// { '--c-token': 'r g b', … } para un bloque de variables.
export function variables(paleta) {
  return Object.fromEntries(Object.entries(paleta).map(([k, v]) => [`--c-${k}`, canales(v)]))
}
